config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Events routes
  get 'events/index'
  get 'events/new'
  get 'events/:id' => 'events#show', as: 'event_show'
  patch 'events/:id' => 'events#update', as: 'event_update'
  get 'events/:id/edit' => 'events#edit', as: 'event_edit'
  get 'events/:id/newTicket', to: 'events#newTicket'
  post 'events/:id/newTicket', to: 'events#createTicket'

  get 'wallet', to: 'users#wallet'
  post 'wallet', to: 'users#topUpWallet'
  get 'user/:id/tickets', to: 'users#showUserTickets'
  
  get 'admin/tickets', to: 'tickets#showAllTickets'
  post 'admin/cancel/ticket/:id', to: 'tickets#returnTicket', as: 'admin_cancel_ticket'
  
  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets
  
  # Set tickets as main page
  root :to => "events#index"
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :tickets

    validates                           :image, attachment_presence: true
    has_attached_file                   :image, default_url: "/images/:style/missing.png"
    validates_attachment_content_type   :image, content_type: /\Aimage\/.*\z/
    validates_attachment_file_name      :image, matches: [/png\z/, /jpe?g\z/]

    validates   :artist, :presence => true
    validates   :description, :presence => true
    validate    :event_date_greater_than_today
    validates   :price_low, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validates   :price_high, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0, less_than: 1000000 }
    validate    :price_high_lower_than_price_low
    validates   :number_of_tickets, :presence => true, numericality: { greater_than: 0}
    validate    :start_selling_date_greater_than_today

    def price_high_lower_than_price_low
        if price_low.present? && price_high.present? && price_low > price_high
            errors.add(:price_high, "can't be lower than price low")
        end
    end

    def start_selling_date_greater_than_today
        if !start_selling_date.present?
            errors.add(:start_selling_date, "can't be empty")
        end
        if start_selling_date.present? && start_selling_date < Date.today
            errors.add(:start_selling_date, "can't be in the past")
        end
        if start_selling_date.present? && event_date.present? && start_selling_date > event_date
            errors.add(:start_selling_date, "can't be after the concert date")
        end
    end    

    def event_date_greater_than_today
        if !event_date.present?
            errors.add(:event_date, "can't be empty")
        end
        if event_date.present? && event_date < Date.today
            errors.add(:event_date, "can't be in the past")
        end
    end    
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper

  before_action :set_event, only: [:show, :edit, :update]
  # before_action :check_logged_in, :only => [:new, :create]
  before_action :check_if_admin?, :only => [:edit, :update]
  before_action :authenticate_user!, :except => [:show, :index]
  before_action :checkEighteenYearsOld, :only => [:show]

  def index
    @events = Event.all
  end

  def show
    @reservedPlaces = Ticket.where(event_id: params[:id]).where(status: [1,2]).pluck(:seat_id_seq, :id)
  end

  def edit
  end

  def new
    @event = Event.new
  end

  def update
    respond_to do |format|
      if @event.update(events_params)
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def newTicket
    @ticket = Ticket.new(:event_id => params[:id])
  end

  def createTicket
    @postValues = ticket_params
    @event = Event.find(@postValues["event_id"])
    @pricePerTicket = calculateEventPrice(@event)
    if (@postValues["seat_id_seq"] != "")
      @seatsArray  = JSON.parse @postValues["seat_id_seq"]
    else
      @seatsArray = []
    end
    
    @currentUserTickets = Ticket.where(user_id: current_user.id).where(event_id: @event.id).where(status: [1,2]).count

    # Ticket for validation
    @ticket = Ticket.new(ticket_params)
    @ticket.user_id = current_user.id

    respond_to do |format|
      if @ticket.validate && current_user.wallet != nil && current_user.wallet >= @seatsArray.count * @pricePerTicket && (@currentUserTickets + @seatsArray.count) <= 5 && @seatsArray.count > 0
          @seatsArray.each do |seat_id|
            @ticket = Ticket.new(ticket_params)
            @ticket.user_id = current_user.id

            @ticket.price = @pricePerTicket
            @ticket.seat_id_seq = seat_id
            @ticket.status = 1
            @ticket.save
          end

          current_user.wallet -= (@seatsArray.count * @pricePerTicket)
          current_user.save
          
        format.html { redirect_to Event.find(params[:id]), notice: 'Tickets bought successfully.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        if current_user.wallet == nil || current_user.wallet < @seatsArray.count * @pricePerTicket
          @ticket.errors.add(:price, "is higher than your wallet")
        end

        if (@currentUserTickets + @seatsArray.count) > 5
          @ticket.errors.add(:seat_id_seq, "max allowed tickets per user are 5")
        end

        if @seatsArray.count == 0
          @ticket.errors.add(:seat_id_seq, "you have to choose the seat")
        end

        @ticket.seat_id_seq = @postValues["seat_id_seq"]
        format.html { render :newTicket }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def showTicket
  end

  def create
    @event = Event.new(events_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def check_logged_in
      authenticate_or_request_with_http_basic("Ads") do |username, password|
        username == "admin" && password == "admin"
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end
    
      # Never trust parameters from the scary internet, only allow the white list through.
      def events_params
        params.require(:event).permit(:artist, :description, :price_low, :price_high, :event_date, :eighteen_years_old, :image, :number_of_tickets, :start_selling_date)
      end
      
      # Never trust parameters from the scary internet, only allow the white list through.
      def ticket_params
        params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
      end

      def check_if_admin?
        redirect_to root_path unless current_user.admin? 
      end

      # Check if user got access to see the event
      def checkEighteenYearsOld
        @event = Event.find(params[:id])
        redirect_to root_path unless (!@event.eighteen_years_old || (user_signed_in? && current_user.eighteen_years_old))
      end
end

app/helpers/events_helper.rb
module EventsHelper
    def calculateTheFine(event, fromDate)
        @daysToEvent = calculateDaysToEvent(event,fromDate)
        
        (@daysToEvent > 31) ? 10 : (@daysToEvent > 21) ? 20 : (@daysToEvent > 11) ? 30 : (@daysToEvent > 5) ? 40 : (@daysToEvent > 2) ? 50 : 60
    end

    def calculateEventPrice(event)
        @daysToEvent = calculateDaysToEvent(event, Date.today)
        
        (@daysToEvent > 31) ? event.price_low : (@daysToEvent > 21) ? event.price_low + (event.price_high - event.price_low)/8 : (@daysToEvent > 11) ? event.price_low + (event.price_high - event.price_low)/4 : (@daysToEvent > 5) ? event.price_low + (event.price_high - event.price_low)/2 : (@daysToEvent > 2) ? event.price_high : event.price_high * 1.20
    end

    def calculateDaysToEvent(event, fromDate)
        ((event.event_date || fromDate)  - fromDate).to_i
    end

    def ticketsLeft(event)
        (event.number_of_tickets || 0) - Ticket.where(event_id: event.id, status: [1,2]).count(:id)
    end
end

app/views/events/_events_list.html.erb
<div class="container">
    <% if (showFilter) %>
        <div class="field form-group row">
            <div class="col-4" style="vertical-align: middle;">
                <label><input type="checkbox" class="showFilters" /> Show filters</label>
            </div>
        </div>
        <div class="filtersContent" style="display: none;">
            <div class="field form-group row">
                <div class="col-2" style="vertical-align: middle;">
                    Date from
                </div>
                <div class="col-2">
                    <input class='date_from form-control' type='date' />
                </div>
            </div>
            <div class="field form-group row">
                <div class="col-2" style="vertical-align: middle;">
                    Date to
                </div>
                <div class="col-2">
                    <input class='date_to form-control' type='date' />
                </div>
            </div>
            <div class="field form-group row">
                <div class="col-2" style="vertical-align: middle;">
                    Artist
                </div>
                <div class="col-2">
                    <input class='artist form-control' />
                </div>
            </div>
        </div>
        <br/>
    <% end %>
    <div class="row">
        <% events.each do |event| %>
            <% if (!event.eighteen_years_old || (user_signed_in? && current_user.eighteen_years_old)) %>
                <div class="card" style="margin: 0 auto; border: 0px;">
                    <%= image_tag event.image.url, :class => "card-img-top", :style => "max-height: 225px;" %>
                    <div class="card-body" style="padding: 10px;">
                        <span class="eventArtist"><%= event.artist %></span> <br/>
                        Event date: <span class="eventDate"><%= event.event_date %></span> <br/>
                        Price: <%= calculateEventPrice(event) %> <br/>
                        <% if(ticketsLeft(event) > 0) %>
                            Tickets left: <%= ticketsLeft(event) %>
                        <% else %>
                            Tickets sold out!
                        <% end %>
                        <br/><br/>
                        <%= link_to 'Show', event, :class => "btn btn-primary" %>
                    </div> 
                </div>
            <% end %>
        <% end %>
    </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true, html: { multipart: true }) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>
  
        <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :artist %>
      </div>
      <div class="col-8">
        <%= form.text_field :artist, id: :event_artist, :class => 'form-control' %>
      </div>
    </div>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :description %>
      </div>
      <div class="col-8">
        <%= form.text_field :description, id: :event_description, :class => 'form-control' %>
      </div>
    </div>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :price_low %>
      </div>
      <div class="input-group col-2">
        <%= form.number_field :price_low, id: :event_price_low, :class => 'form-control' %>
        <span class="input-group-addon">zł</span>
      </div>
    </div>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :price_high %>
      </div>
      <div class="input-group col-2">
        <%= form.number_field :price_high, id: :event_price_high, :class => 'form-control' %>
        <span class="input-group-addon">zł</span>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :event_date %>
      </div>
      <div class="col-3">
        <%= form.date_field :event_date, id: :event_event_date, :class => 'form-control' %>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :number_of_tickets %>
      </div>
      <div class="col-2">
        <%= form.number_field :number_of_tickets, id: :event_number_of_tickets, :class => 'form-control' %>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :start_selling_date %>
      </div>
      <div class="col-3">
        <%= form.date_field :start_selling_date, id: :event_start_selling_date, :class => 'form-control' %>
      </div>
    </div>

    <div class="field form-group row">
      <div class="col-4">
        <%= form.check_box :eighteen_years_old%>
        <%= form.label :eighteen_years_old_required%>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-5">
        <%= form.file_field :image, :class => 'form-control-file' %>
      </div>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/edit.html.erb
<h3>Edit Event</h3>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<%= javascript_include_tag "/javascript/events.js" %>

<h3>Events</h3>
<br/>
<%= render 'events/events_list', events: Event.where("event_date >= ?", Date.today).where("start_selling_date <= ?", Date.today), showFilter: true %>
<br/>

<% if (user_signed_in? && current_user.admin) %> 
  <h3>Archival events</h3>
  <br/>
  <%= render 'events/events_list', events: Event.where("event_date < ?", Date.today), showFilter: false %>
  <br/>
  <%= link_to 'New event', new_event_path, :class => 'btn btn-primary' %>
<% end %>

app/views/events/new.html.erb
<h3>New Event</h3>
<%= render 'form', event: @event %>

app/views/events/newTicket.html.erb
<%= javascript_include_tag "/javascript/events.js" %>
<%= render 'tickets/new_ticket', ticket: @ticket, reservedPlaces:  Ticket.where(event_id: params[:id]).where(status: [1,2]).pluck(:seat_id_seq), actionPath: "/events/#{params[:id]}/newTicket"%>

app/views/events/show.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-4">
      <%= image_tag @event.image.url, :size => "320x225" %>
    </div>
  </div>

  <br/>
  <div class="row  justify-content-center">
    <div class="col-2">
      <strong>Artist:</strong>
    </div>
    <div class="col-2">
      <%= @event.artist %>
    </div>
  </div>


  <div class="row justify-content-center">
    <div class="col-2 offset-md-4">
      <strong>Description:</strong>
    </div>
    <div class="col-6">
      <%= @event.description %>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Price:</strong>
    </div>
    <div class="col-2">
      <%= calculateEventPrice(@event) %>zł
    </div>
  </div>
  
  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Event date:</strong>
    </div>
    <div class="col-2">
      <%= @event.event_date %>
    </div>
  </div>
  
  <div class="row justify-content-center">
    <% if(ticketsLeft(@event) > 0) %>
      <div class="col-2">
        <strong>Tickets left:</strong>
      </div>
      <div class="col-2">
        <%= ticketsLeft(@event) %>
      </div>
    <% else %>
      <div class="col-4 text-center">
        Tickets sold out!
      </div>
    <% end %>
  </div>

  <% if (user_signed_in? && current_user.admin) %>
    <br/>
    <div class="field form-group row col-7  justify-content-center" style="margin: 0 auto; max-height: 300px; overflow-y: auto;">
      <% (0..@event.number_of_tickets-1).each do |i| %>
        <% @seatNumber = "#{(65 + i / 10).chr}#{i -  (i / 10) * 10}" %>
        <% @currentTicket = (@reservedPlaces.select{|place| place[0] == @seatNumber}).first %>
        <div seat_number="<%= @seatNumber %>" class="card seat<%= (@currentTicket != nil) ? ' reserved' : ''%>">
          <div class="card-body" style=" display: table-cell; vertical-align: middle; text-align: center;">  
            <% if @currentTicket != nil %>
              <%= link_to ticket_url(@currentTicket[1]) do %>
                <%= @seatNumber %>
              <% end %>
            <% else %>
              <%= @seatNumber %>
            <% end %>
          </div>
        </div>    
      <% end %>
    </div>
  <% end %>

  <div class="row justify-content-center">
    <div class="col-4 text-center">
      <% if (user_signed_in? && @event.event_date >= Date.today && ticketsLeft(@event) > 0) %> 
        <br/>
        <%= link_to 'Buy ticket', "/events/#{@event.id}/newTicket", :class => 'btn btn-primary' %>
        <% if current_user.admin %>
          <%= link_to 'Modify', "/events/#{@event.id}/edit", :class => 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

<br/><br/>
<%= render 'tickets/tickets_list', tickets: Ticket.where(event_id: @event.id) %>