config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Events routes
  get 'events/index'
  get 'events/new'
  get 'events/:id' => 'events#show', as: 'event_show'
  patch 'events/:id' => 'events#update', as: 'event_update'
  get 'events/:id/edit' => 'events#edit', as: 'event_edit'
  get 'events/:id/newTicket', to: 'events#newTicket'
  post 'events/:id/newTicket', to: 'events#createTicket'

  get 'wallet', to: 'users#wallet'
  post 'wallet', to: 'users#topUpWallet'
  get 'user/:id/tickets', to: 'users#showUserTickets'
  
  get 'admin/tickets', to: 'tickets#showAllTickets'
  post 'admin/cancel/ticket/:id', to: 'tickets#returnTicket', as: 'admin_cancel_ticket'
  
  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets
  
  # Set tickets as main page
  root :to => "events#index"
end

app/models/ticket.rb
class Ticket < ApplicationRecord
    belongs_to :event
    belongs_to :user

    validates :phone, :presence => true, format: {with: /\A[+-]?\d+\z/}
    validates_length_of :phone, :minimum => 7, :maximum => 13
    validates :email_address, :presence => true
    validates :price, presence: true, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }
    
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :check_if_admin?, :only => [:showAllTickets, :returnTicket]

  include EventsHelper
  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  def showAllTickets
    @tickets = Ticket.all.order(created_at: :desc)
  end

  def returnTicket
    @ticket = Ticket.find(params[:id])
    @event = Event.find(@ticket.event_id)
    @user = User.find(@ticket.user_id)

    @userFine = calculateTheFine(@event, @ticket.updated_at.to_date)

    @user.wallet = (@user.wallet || 0) + (@ticket.price * (100 - @userFine))/100
    @ticket.status = 3

    respond_to do |format|
      if calculateDaysToEvent(@event, @ticket.updated_at.to_date) > 0 && @user.save && @ticket.save
        format.html { redirect_to admin_tickets_path, notice: "Ticket was returned successfully."}
        format.json { head :no_content }
      else
        format.html { redirect_to admin_tickets_path, alert: "You cannot return this ticket"}
        format.json { head :no_content }
      end
    end
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    if @ticket.price <= current_user.wallet
      @ticket.user_id = current_user.id
      @ticket.status = 1

      respond_to do |format|
        if @ticket.save
          format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
          format.json { render :show, status: :created, location: @ticket }
        else
          format.html { render :new }
          format.json { render json: @ticket.errors, status: :unprocessable_entity }
        end
      end
    else
      format.html { render :new }
      format.json { render json: @ticket.errors, status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.status = 2
    @ticket.save
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket return request has been sent successfully.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:name, :seat_id_seq, :address, :price, :email_address, :phone, :event_id)
    end
    
    def check_if_admin?
      redirect_to root_path unless current_user.admin? 
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_new_ticket.html.erb
<%= form_with(model: ticket, local: true, url: actionPath) do |form| %>
    <% if ticket.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>
  
        <ul>
        <% ticket.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :address, :class => 'col-form-label'  %>
      </div>
      <div class="col-8">
        <%= form.text_area :address, id: :ticket_address, :class => 'form-control' %>
        </div>
    </div>
  
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :price, :class => 'col-form-label'  %>
      </div>
      <div class="input-group col-3">
        <%= form.number_field :price, id: :ticket_price, :class => 'form-control', :step => 0.01, :value => 0.00, :readonly => true, :cost_per_ticket => calculateEventPrice(Event.find(params[:id])) %>
        <span class="input-group-addon">zł</span>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :email_address, :class => 'col-form-label'  %>
      </div>
      <div class="col-8">
        <%= form.text_field :email_address, id: :ticket_email_address, :class => 'form-control', :value => current_user.email, :readonly => true %>
      </div>
    </div>
    
    <div class="field form-group row">
      <div class="col-2">
        <%= form.label :phone, :class => 'col-form-label'  %>
      </div>
      <div class="col-8">
        <%= form.text_field :phone, id: :ticket_phone, :class => 'form-control' %>
      </div>
    </div>
    
    <div class="field form-group row">

        <% if (actionPath.include? "tickets") %>
            <div class="col-2">
              <%= form.label :event_id, id: :ticket_event_id, :class => 'col-form-label' %>
            </div>
            <div class="col-8">
              <%= form.collection_select :event_id, Event.all.select("artist, id"), :id, :artist, {}, {class: 'form-control'}%>
            </div>
        <% else %>
            <%= form.hidden_field :event_id, id: :ticket_event_id%>
        <% end %>
    </div>

    <div class="field form-group row col-6" style="margin: 0 auto; max-height: 300px; overflow-y: auto;">
        <%= form.hidden_field :seat_id_seq, id: :ticket_seat_id_seq %>
        <% (0..Event.find(params[:id])['number_of_tickets']-1).each do |i| %>
          <% @seatNumber = "#{(65 + i / 10).chr}#{i -  (i / 10) * 10}" %>
          <div seat_number="<%= @seatNumber %>" class="card seat<%= (reservedPlaces.include?(@seatNumber)) ? ' reserved' : ''%>">
            <div class="card-body" style=" display: table-cell; vertical-align: middle; text-align: center;">  
              <%= @seatNumber %>
            </div>
          </div>    
        <% end %>
    </div>
    <div class="actions">
      <% if (actionPath.include? "events") %>
        <%= link_to 'Back', "/events/#{params[:id]}", :class => 'btn btn-primary'%>
      <% end %>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/tickets/_tickets_list.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Artist</th>
      <th>Seat id seq</th>
      <th>Address</th>
      <th>Price</th>
      <th>Email address</th>
      <th>Phone</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% tickets.each do |ticket| %>
      <tr class="<%= (ticket.status == 2) ? 'requestForReturn' : (ticket.status == 3) ? 'returned' : ''%>">
        <td>
          <%= link_to event_show_path(ticket.event_id) do %>
            <%= Event.find(ticket.event_id).artist%>
          <% end %>
        </td>
        <td><%= ticket.seat_id_seq %></td>
        <td><%= ticket.address %></td>
        <td><%= ticket.price %></td>
        <td><%= link_to(ticket.email_address, "/user/#{ticket.user_id}/tickets")  %></td>
        <td><%= ticket.phone %></td>
        
        <% if (current_page?(tickets_path) && ticket.status == 1) %>
          <td style="text-align: center;">
            <%= link_to ticket, :class => 'btn-sm btn-primary' do %>
              Show
            <% end %>
          </td>
          <td style="text-align: center;">
            <%= link_to ticket, method: :delete, :class => 'btn-sm btn-danger', data: { confirm: "Are you sure?\nYou will loose #{calculateTheFine(Event.find(ticket.event_id), Date.today)}% of the ticket price." } do %>
              Return
            <% end %>
          </td>
        <% else %>
          <td colspan=2 style="text-align: center;">
            <% if (ticket.status == 2 && user_signed_in? && current_user.admin && currentPath(admin_tickets_path)) %>
              <%= link_to "#{admin_cancel_ticket_path(ticket.id)}", method: :post, :class => 'btn-sm btn-danger', data: { confirm: "Are you sure? The ticket will be returned." } do %>
                Approve
              <% end %>
            <% else %>
                  <%= (ticket.status == 2) ? 'Request waiting for acceptance' : (ticket.status == 3) ? 'Returned' : '' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/tickets/edit.html.erb
<h3>Editing Ticket</h3>

<%= render 'new_ticket', ticket: @ticket, actionPath: "/tickets/#{params[:id]}" %>

app/views/tickets/index.html.erb
<h3>My Tickets</h3>
<br/>
<%= render 'tickets_list', tickets: Ticket.where(user_id: current_user.id) %>

app/views/tickets/new.html.erb
<h3>New Ticket</h3>

<%= render 'new_ticket', ticket: @ticket, actionPath: tickets_path %>

app/views/tickets/show.html.erb
<div class="container">

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Artist:</strong>
    </div>
    <div class="col-2">
    <%= link_to event_show_path(@ticket.event_id) do %>
      <%= Event.find(@ticket.event_id).artist%>
    <% end %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Email address:</strong>
    </div>
    <div class="col-2">
      <%= link_to(@ticket.email_address, "/user/#{@ticket.user_id}/tickets") %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Address:</strong>
    </div>
    <div class="col-2">
    <%= @ticket.address %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Phone:</strong>
    </div>
    <div class="col-2">
    <%= @ticket.phone %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Seat in the audience:</strong>
    </div>
    <div class="col-2">
    <%= @ticket.seat_id_seq %>
    </div>
  </div>

  <div class="row justify-content-center">
    <div class="col-2">
      <strong>Ticket price:</strong>
    </div>
    <div class="col-2">
    <%= @ticket.price %>
    </div>
  </div>

  <br/>
  <div class="row justify-content-center">
    <div class="col-4 text-center">
      <%= link_to 'Back', tickets_path, :class => 'btn btn-primary' %>
    </div>
  </div>

app/views/tickets/showAllTickets.html.erb
<h3>All tickets</h3>
<br/>
<%= render 'tickets_list', tickets: @tickets %>