config/routes.rb
Rails.application.routes.draw do
  
  # devise_for :users
  devise_for :users, :controllers => { registrations: 'registrations' }
  # Events routes
  get 'events/index'
  get 'events/new'
  get 'events/:id' => 'events#show', as: 'event_show'
  patch 'events/:id' => 'events#update', as: 'event_update'
  get 'events/:id/edit' => 'events#edit', as: 'event_edit'
  get 'events/:id/newTicket', to: 'events#newTicket'
  post 'events/:id/newTicket', to: 'events#createTicket'

  get 'wallet', to: 'users#wallet'
  post 'wallet', to: 'users#topUpWallet'
  get 'user/:id/tickets', to: 'users#showUserTickets'
  
  get 'admin/tickets', to: 'tickets#showAllTickets'
  post 'admin/cancel/ticket/:id', to: 'tickets#returnTicket', as: 'admin_cancel_ticket'
  
  resources :events, :only => [:index, :new, :create, :show]
  resources :tickets
  
  # Set tickets as main page
  root :to => "events#index"
end

app/views/layouts/pageElements/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse bg-primary">
  <div class="collapse navbar-collapse">
    <ul class="nav navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Events", events_url, :class => "#{currentPath(events_url)} nav-link" %>
      </li>
      <% if user_signed_in? %>  
        <li class="nav-item">
          <%= link_to "My Tickets", tickets_url, :class => "#{currentPath(tickets_url)} nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My Wallet", wallet_path, :class => "#{currentPath(wallet_path)} nav-link" %>
        </li>
        <% if current_user.admin %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenu" data-toggle="dropdown">
              Admin
            </a>
            <div class="dropdown-menu dropdown-primary" aria-labelledby="dropdownMenu">
              <%= link_to("All tickets", admin_tickets_path, :class => "dropdown-item") %>
            </div>
          </li>
        <% end %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <% if user_signed_in? %>  
        <li class="nav-item">
          <a class="nav-link active" href="#">Logged In as <strong><%= current_user.email %></strong></a>
        </li>
        <li class="nav-item">
          <%= link_to "Edit profile", edit_user_registration_path, :class => "#{currentPath(edit_user_registration_path)} nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, :method => :delete, :class => "#{currentPath(destroy_user_session_path)} nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to new_user_registration_path, :class => "#{currentPath(new_user_registration_path)} nav-link" do %>
            <%= fa_icon "user" %> Sign Up
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, :class => "#{currentPath(new_user_session_path)} nav-link" do %>
            <%= fa_icon "sign-in" %> Log In
            <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/pageElements/_noticeCatcher.html.erb
<% if notice %>
    <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
<% end %>